
version: "3.8"
services:
  akashichub-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: akashichub-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: a_strong_root_password
      MYSQL_DATABASE: akashichub_db
      MYSQL_USER: akashic_user
      MYSQL_PASSWORD: akashic_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  akashichub-seq:
    image: datalust/seq:latest
    container_name: akashichub-seq
    restart: always
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "8081:80"
      - "5341:5341"
    volumes:
      - seq_data:/data

  akashichub-api:
    build: ./akashichub-api
    container_name: akashichub-api
    restart: always
    env_file:
      - ./akashichub-api/.env
    depends_on:
      - akashichub-db
      - akashichub-seq
    ports:
      - "3000:3000"
    volumes:
      - ./akashichub-api:/app


volumes:
  db_data:
  seq_data:
