/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBreadcrumb: typeof import('./src/components/Layout/AppBreadcrumb.vue')['default']
    AppFooter: typeof import('./src/components/Layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/Layout/AppHeader.vue')['default']
    AppSettings: typeof import('./src/components/Layout/AppSettings.vue')['default']
    AppSidebar: typeof import('./src/components/Layout/AppSidebar.vue')['default']
    AppTabs: typeof import('./src/components/Layout/AppTabs.vue')['default']
    GlobalSearch: typeof import('./src/components/Search/GlobalSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
